// packages/minuta-svelte/src/components/CalendarExample.svelte
<script lang="ts">
  import { derived, get, writable } from "svelte/store";
  import type { Period } from "minuta";
  import { createNativeAdapter } from "minuta/native";
  import { createMinuta } from "../createMinuta";
  import { usePeriod } from "../usePeriod";
  import Navigator from "./Navigator.svelte";

  const date = writable(new Date());
  const now = writable(new Date());

  const temporal = createMinuta({
    adapter: createNativeAdapter({ weekStartsOn: 1 }),
    date,
    now,
    locale: "en",
  });

  const month = usePeriod(temporal, "month");
  const weekPeriods = derived(month, ($month) =>
    temporal.divide($month, "week")
  );
  const dayPeriods = derived(weekPeriods, ($weeks) =>
    $weeks.flatMap((week) => temporal.divide(week, "day"))
  );

  const monthLabel = derived(month, ($month) =>
    $month.start.toLocaleDateString(temporal.locale, {
      month: "long",
      year: "numeric",
    })
  );

  const weekdayLabels = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
  const browsing = temporal.browsing;

  function select(day: Period) {
    temporal.browsing.set(day);
  }

  function isCurrentMonth(day: Period) {
    return temporal.isSame(day, get(month), "month");
  }

  function isToday(day: Period) {
    return temporal.isSame(day, get(browsing), "day");
  }
</script>

<main>
  <section class="panel">
    <div>
      <h1>{$monthLabel}</h1>
      <p class="legend">Browse months and click a day to change the browsing period.</p>
    </div>

    <Navigator {month} />

    <div class="weekday-row">
      {#each weekdayLabels as label}
        <span>{label}</span>
      {/each}
    </div>

    <div class="grid">
      {#each $dayPeriods as day}
        <div
          class="day {isCurrentMonth(day) ? '' : 'inactive'} {isToday(day) ? 'selected' : ''}"
        >
          <button type="button" on:click={() => select(day)}>
            <span class="date-label">{day.start.getDate()}</span>
            <small>{day.start.toLocaleDateString(temporal.locale, { weekday: "short" })}</small>
          </button>
        </div>
      {/each}
    </div>
  </section>
</main>

// packages/minuta-react/src/components/CalendarExample.tsx
import { useMemo, useState, type Dispatch, type SetStateAction } from "react";
import type { Period } from "minuta";
import { createNativeAdapter } from "minuta/native";
import { useMinuta } from "../useMinuta";
import { usePeriod } from "../usePeriod";
import type { MinutaBuilder } from "../types";

const WEEKDAY_ORDER: Record<0 | 1, string[]> = {
  0: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  1: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
};

const dayFormatter = new Intl.DateTimeFormat("en-US", {
  weekday: "short",
});

const monthFormatter = new Intl.DateTimeFormat("en-US", {
  month: "long",
  year: "numeric",
});

const rangeFormatter = new Intl.DateTimeFormat("en-US", {
  month: "short",
  day: "numeric",
});

type WeekWithDays = { period: Period; days: Period[] };

/**
 * Batteries-included calendar that mirrors the React example app.
 * Ship it from the package so docs + sandboxes can import it directly.
 */
export function CalendarExample() {
  const [weekStartsOn, setWeekStartsOn] = useState<0 | 1>(1);

  // PATTERN: Memoize adapters so React recreates them when config changes.
  const adapter = useMemo(
    () => createNativeAdapter({ weekStartsOn }),
    [weekStartsOn]
  );

  const temporal = useMinuta({
    adapter,
    date: new Date(),
  });

  const month = usePeriod(temporal, "month");

  const weeks = useMemo<WeekWithDays[]>(
    () => buildWeeks(temporal, month),
    [temporal, month]
  );
  const weekdayLabels = WEEKDAY_ORDER[weekStartsOn];

  return (
    <section className="calendar-shell" data-testid="calendar-example">
      <header className="calendar-header">
        <div>
          <h1>useTemporal React Demo</h1>
          <p className="subheading">
            Derived periods, divide() pattern, and adapter reactivity in one
            hook.
          </p>
        </div>
        <WeekStartToggle
          weekStartsOn={weekStartsOn}
          onChange={setWeekStartsOn}
        />
      </header>

      <PeriodDisplay month={month} now={temporal.now} />

      <NavigationControls temporal={temporal} targetPeriod={month} />

      <div className="weekday-grid">
        {weekdayLabels.map((weekday) => (
          <span key={weekday}>{weekday}</span>
        ))}
      </div>

      <div className="weeks-grid">
        {weeks.map((week) => (
          <div key={week.period.start.toISOString()} className="week-row">
            {week.days.map((day) => {
              const isOutside = !temporal.contains(month, day.start);
              const isToday = temporal.isSame(day, temporal.now, "day");
              return (
                <button
                  type="button"
                  key={day.start.toISOString()}
                  className={[
                    "day-cell",
                    isOutside ? "is-outside" : "",
                    isToday ? "is-today" : "",
                  ]
                    .filter(Boolean)
                    .join(" ")}
                  onClick={() => temporal.go(day, 0)}
                  title={dayFormatter.format(day.start)}
                >
                  <span className="date-number">{day.start.getDate()}</span>
                  <span className="weekday-label">
                    {dayFormatter.format(day.start)}
                  </span>
                </button>
              );
            })}
          </div>
        ))}
      </div>
    </section>
  );
}

function buildWeeks(temporal: MinutaBuilder, month: Period): WeekWithDays[] {
  return temporal.divide(month, "week").map((week) => ({
    period: week,
    days: temporal.divide(week, "day"),
  }));
}

function NavigationControls({
  temporal,
  targetPeriod,
}: {
  temporal: MinutaBuilder;
  targetPeriod: Period;
}) {
  return (
    <div className="toolbar-row">
      <button
        type="button"
        className="nav-button"
        onClick={() => temporal.previous(targetPeriod)}
      >
        ← Previous
      </button>
      <button
        type="button"
        className="nav-button"
        onClick={() => temporal.next(targetPeriod)}
      >
        Next →
      </button>
    </div>
  );
}

function PeriodDisplay({ month, now }: { month: Period; now: Period }) {
  const label = monthFormatter.format(month.start);
  const isCurrentMonth =
    month.start.getFullYear() === now.start.getFullYear() &&
    month.start.getMonth() === now.start.getMonth();

  return (
    <div className="period-display">
      <div>
        <p className="eyebrow">Browsing</p>
        <h2>{label}</h2>
      </div>
      <dl>
        <div>
          <dt>Range</dt>
          <dd>
            {rangeFormatter.format(month.start)} –{" "}
            {rangeFormatter.format(month.end)}
          </dd>
        </div>
        <div>
          <dt>Status</dt>
          <dd>{isCurrentMonth ? "Current month" : "Historical view"}</dd>
        </div>
      </dl>
    </div>
  );
}

function WeekStartToggle({
  weekStartsOn,
  onChange,
}: {
  weekStartsOn: 0 | 1;
  onChange: Dispatch<SetStateAction<0 | 1>>;
}) {
  return (
    <div className="toolbar-section">
      <p className="toolbar-label">Week starts on</p>
      <div className="toggle-group">
        <button
          type="button"
          className={weekStartsOn === 0 ? "toggle is-active" : "toggle"}
          onClick={() => onChange(0)}
        >
          Sunday
        </button>
        <button
          type="button"
          className={weekStartsOn === 1 ? "toggle is-active" : "toggle"}
          onClick={() => onChange(1)}
        >
          Monday
        </button>
      </div>
    </div>
  );
}
